Use bash

diff --git a/bin/create-vm b/bin/create-vm
--- a/bin/create-vm
+++ b/bin/create-vm
@@ -1,3 +1,8 @@
+#!/bin/bash
+
+# Exit on failure
+set -e
+
 # ARGS
 
 VERSION="${1}"
@@ -14,7 +19,8 @@ DISK_SIZE="50G"
 
 # VALIDATE
 
-if [ "${VM_ID}" = "" |  "${VM_ID}" -lt "100" | "${VM_ID}" -gt "253" ]; then
+if [ "${VM_ID}" = "" |  "${VM_ID}" -lt "100" | "${VM_ID}" -gt "253" ];
+then
     echo "ERROR: Invalid VM_ID: ${VM_ID}"
     exit 1
 fi
@@ -30,9 +36,6 @@ echo "CORES: ${CORES}"
 echo "DISK_SIZE: ${DISK_SIZE}"
 
 # START
-
-# Exit on failure
-set -e
 
 echo "##### Create a virtual machine:"
 qm create ${VM_ID} --memory ${MEM_SIZE} --name ubuntu-cloud-${UBUNTU_DISTRO} --net0 virtio,bridge=vmbr0
diff --git a/bin/download-distro b/bin/download-distro
--- a/bin/download-distro
+++ b/bin/download-distro
@@ -1,3 +1,8 @@
+#!/bin/bash
+
+# Exit on failure
+set -e
+
 # ARGS
 
 VERSION="${1}"
@@ -21,9 +26,6 @@ echo "FILENAME: ${FILENAME}"
 echo "URL: ${URL}"
 
 # START
-
-# Exit on failure
-set -e
 
 echo "##### Download the Ubuntu cloud image"
 wget ${URL}
diff --git a/bin/write-cloud-config b/bin/write-cloud-config
--- a/bin/write-cloud-config
+++ b/bin/write-cloud-config
@@ -1,4 +1,7 @@
-# ARGS
+#!/bin/bash
+
+# Exit on failure
+set -e
 
 VM_ID="${1}"
 
@@ -39,9 +42,6 @@ echo "USER: ${USER}"
 echo "SUDO_USER: ${SUDO_USER}"
 
 # START
-
-# Exit on failure
-set -e
 
 echo "##### Copy cloud config"
 cp ${CONFIG_SRC}  ${CONFIG_FILE}
