Improve consistency of error messages

diff --git a/bin/download-distro b/bin/download-distro
--- a/bin/download-distro
+++ b/bin/download-distro
@@ -15,8 +15,8 @@ URL="https://cloud-images.ubuntu.com/${VERSION}/current/${FILENAME}"
 # VALIDATE
 
 if [ "${VERSION}" = "" ]; then
-    echo "ERROR: Argument 1 (VERSION) was not provided. Try calling with: jammy" >&2
-    exit 1
+  echo "❗  Invalid VERSION: ${VERSION}" >&2
+  exit 1
 fi
 
 # START
diff --git a/lib/create-proxmox-vm b/lib/create-proxmox-vm
--- a/lib/create-proxmox-vm
+++ b/lib/create-proxmox-vm
@@ -22,13 +22,13 @@ STORAGE_NAME="local"
 
 if [[ "${ID}" = "" ||  "${ID}" -lt "100" || "${ID}" -gt "253" ]];
 then
-    echo "ERROR: Invalid ID: ${ID}" >&2
+    echo "❗  Invalid ID: ${ID}" >&2
     exit 1
 fi
 
 if [[ "${MEMORY}" = "" || "${MEMORY}" -lt "1" || "${MEMORY}" -gt "32" ]];
 then
-    echo "ERROR: Invalid MEMORY: ${MEMORY}" >&2
+    echo "❗  Invalid MEMORY: ${MEMORY}" >&2
     exit 1
 else
     MEMORY=$((${MEMORY} * 1024))
@@ -36,13 +36,13 @@ fi
 
 if [[ "${CORES}" = "" || "${CORES}" -lt "1" || "${CORES}" -gt "4" ]];
 then
-    echo "ERROR: Invalid CORES: ${CORES}" >&2
+    echo "❗  Invalid CORES: ${CORES}" >&2
     exit 1
 fi
 
 if [[ "${DISK_SIZE}" = "" ||  "${DISK_SIZE}" -lt "20" || "${DISK_SIZE}" -gt "4000" ]];
 then
-    echo "ERROR: Invalid DISK_SIZE: ${DISK_SIZE}" >&2
+    echo "❗  Invalid DISK_SIZE: ${DISK_SIZE}" >&2
     exit 1
 else
     DISK_SIZE="${DISK_SIZE}G"
@@ -50,7 +50,7 @@ fi
 
 if [[ "${IMG_FILE}" = "" || ! -f "${IMG_FILE}" ]];
 then
-    echo "ERROR: Invalid IMG_FILE: ${IMG_FILE}" >&2
+    echo "❗  Invalid IMG_FILE: ${IMG_FILE}" >&2
     exit 1
 fi
 
@@ -66,39 +66,39 @@ fi
 
 # START
 
-echo "##### Create a virtual machine"
+echo "🆕  Create a virtual machine"
 qm create ${ID} --name ${NAME} --tags ${TAGS}
 qm set ${ID} --memory ${MEMORY}
 qm set ${ID} --sockets 1 --cores ${CORES}
 qm set ${ID} --net0 virtio,bridge=vmbr0
 qm set ${ID} --agent enabled=1
 
-echo "##### Import the disk into the proxmox storage"
+echo "➡️  Import the disk into the proxmox storage"
 qm importdisk ${ID} ${IMG_FILE} ${STORAGE_NAME}
 
-echo "##### Add the imported disk to the VM"
+echo "➡️  Add the imported disk to the VM"
 qm set ${ID} \
     --scsihw virtio-scsi-pci \
     --scsi0 ${STORAGE_NAME}:${ID}/vm-${ID}-disk-0.raw
 
-echo "##### Specify the boot disk"
+echo "➡️  Specify the boot disk"
 qm set ${ID} --boot c --bootdisk scsi0
 
-echo "##### Add support for VNC and a serial console"
+echo "➡️  Add support for VNC and a serial console"
 qm set ${ID} --serial0 socket --vga serial0
 
-echo "##### Add a CD-ROM for cloud-init"
+echo "➡️  Add a CD-ROM for cloud-init"
 qm set ${ID} --ide2 ${STORAGE_NAME}:cloudinit
 
-echo "##### Set cloud-init"
+echo "➡️  Set cloud-init"
 qm set ${ID} --cicustom \
     "network=local:snippets/${ID}-network-config.yml,user=local:snippets/${ID}-user-config.yml"
 
-echo "##### Write user config"
-"/srv/lib/write-user-config" "/var/lib/vz/snippets/${ID}-user-config.yml" ${HOSTNAME} 
+echo "➡️  Write user config"
+/srv/lib/write-user-config "/var/lib/vz/snippets/${ID}-user-config.yml" ${HOSTNAME} 
 
-echo "##### Write network config"
-"/srv/lib/write-network-config" "/var/lib/vz/snippets/${ID}-network-config.yml" ${ID}
+echo "➡️  Write network config"
+/srv/lib/write-network-config "/var/lib/vz/snippets/${ID}-network-config.yml" ${ID}
 
-# echo "##### Resize boot disk"
+# echo "➡️  Resize boot disk"
 # qm disk resize ${ID} scsi0 ${DISK_SIZE}
diff --git a/lib/write-network-config b/lib/write-network-config
--- a/lib/write-network-config
+++ b/lib/write-network-config
@@ -17,7 +17,7 @@ GATEWAY_IP="10.10.10.1"
 
 if [[ "${VM_ID}" = "" || "${VM_ID}" -lt "100" || "${VM_ID}" -gt "253" ]];
 then
-    echo "ERROR: Invalid VM_ID: ${VM_ID}" >&2
+    echo "❗  Invalid VM_ID: ${VM_ID}" >&2
     exit 1
 fi
 
diff --git a/lib/write-user-config b/lib/write-user-config
--- a/lib/write-user-config
+++ b/lib/write-user-config
@@ -17,7 +17,7 @@ SSH_PORT="4444"
 
 if [[ "${HOSTNAME}" = "" ]];
 then
-    echo "ERROR: Invalid HOSTNAME: ${HOSTNAME}" >&2
+    echo "❗  Invalid HOSTNAME: ${HOSTNAME}" >&2
     exit 1
 fi
 
@@ -29,6 +29,6 @@ sed -i 's/${USER}/'${USER}'/' ${CONFIG_FILE}
 sed -i 's/${SUDO_USER}/'${SUDO_USER}'/' ${CONFIG_FILE}
 "/srv/lib/yaml-embed-array" ${CONFIG_FILE} "/root/.ssh/id_rsa.pub" "\${SSH_AUTHORIZED_KEYS}" 3
 sed -i 's/${SSH_PORT}/'${SSH_PORT}'/' ${CONFIG_FILE}
-"/srv/lib/yaml-embed-block" ${CONFIG_FILE} "/srv/src/50-hello-world" "\${HELLO_WORLD_CONTENT}"
-"/srv/lib/yaml-embed-array" ${CONFIG_FILE} "/srv/src/bootcmd.sh" "\${BOOTCMD_CONTENT}" 1
-"/srv/lib/yaml-embed-array" ${CONFIG_FILE} "/srv/src/runcmd.sh" "\${RUNCMD_CONTENT}" 1
+/srv/lib/yaml-embed-block ${CONFIG_FILE} "/srv/src/50-hello-world" "\${HELLO_WORLD_CONTENT}"
+/srv/lib/yaml-embed-array ${CONFIG_FILE} "/srv/src/bootcmd.sh" "\${BOOTCMD_CONTENT}" 1
+/srv/lib/yaml-embed-array ${CONFIG_FILE} "/srv/src/runcmd.sh" "\${RUNCMD_CONTENT}" 1
diff --git a/lib/yaml-embed-array b/lib/yaml-embed-array
--- a/lib/yaml-embed-array
+++ b/lib/yaml-embed-array
@@ -14,13 +14,23 @@ TEMP_FILE=$(mktemp)
 
 # VALIDATE
 
-if [ "${SOURCE_FILE}" = "" ]; then
-  echo "ERROR: Invalid SOURCE_FILE: ${SOURCE_FILE}" >&2
+if [[ ! -f "${SOURCE_FILE}" ]]; then
+  echo "❗  Invalid SOURCE_FILE: ${SOURCE_FILE}" >&2
   exit 1
 fi
 
-if [ "${INDENT_COUNT}" = "" ]; then
-  echo "ERROR: Invalid INDENT: ${INDENT_COUNT}" >&2
+if [[ ! -f "${INSERT_FROM_FILE}" ]]; then
+  echo "❗  Invalid INSERT_FROM_FILE: ${INSERT_FROM_FILE}" >&2
+  exit 1
+fi
+
+if [[ "${FIND}" = "" ]]; then
+  echo "❗  Invalid FIND: ${FIND}" >&2
+  exit 1
+fi
+
+if [[ "${INDENT_COUNT}" = "" ]]; then
+  echo "❗  Invalid INDENT_COUNT: ${INDENT_COUNT}" >&2
   exit 1
 fi
 
diff --git a/lib/yaml-embed-block b/lib/yaml-embed-block
--- a/lib/yaml-embed-block
+++ b/lib/yaml-embed-block
@@ -13,8 +13,18 @@ TEMP_FILE=$(mktemp)
 
 # VALIDATE
 
-if [ "${SOURCE_FILE}" = "" ]; then
-  echo "ERROR: Invalid SOURCE_FILE: ${SOURCE_FILE}" >&2
+if [[ ! -f "${SOURCE_FILE}" ]]; then
+  echo "❗  Invalid SOURCE_FILE: ${SOURCE_FILE}" >&2
+  exit 1
+fi
+
+if [[ ! -f "${INSERT_FROM_FILE}" ]]; then
+  echo "❗  Invalid INSERT_FROM_FILE: ${INSERT_FROM_FILE}" >&2
+  exit 1
+fi
+
+if [[ "${FIND}" = "" ]]; then
+  echo "❗  Invalid FIND: ${FIND}" >&2
   exit 1
 fi
 
diff --git a/tests/run-test b/tests/run-test
--- a/tests/run-test
+++ b/tests/run-test
@@ -14,7 +14,7 @@ ACTUAL_FILE="/srv/tests/actual${SCRIPT_FILE}"
 
 if [[ ! -f ${SCRIPT_FILE} ]];
 then
-  echo "❗ Failed to run test. SCRIPT_FILE does not exist: ${SCRIPT_FILE}" >&2
+  echo "❗  Invalid SCRIPT_FILE: ${SCRIPT_FILE}" >&2
   exit 1
 fi
 
@@ -40,7 +40,7 @@ elif [[ "${SCRIPT_FILE}" == "/srv/lib/write-user-config" ]];
 then
   ARGUMENTS="vm999"
 else
-  echo "❗ Failed to run test. Unknown SCRIPT_FILE: ${SCRIPT_FILE}" >&2
+  echo "❗  Unknown SCRIPT_FILE: ${SCRIPT_FILE}" >&2
   exit 1
 fi
 
diff --git a/tests/update-expected b/tests/update-expected
--- a/tests/update-expected
+++ b/tests/update-expected
@@ -13,19 +13,19 @@ ACTUAL_FILE="/srv/tests/actual${SCRIPT_FILE}"
 
 if [[ ! -f ${SCRIPT_FILE} ]];
 then
-  echo "❗ Failed to update expected test. SCRIPT_FILE does not exist: ${SCRIPT_FILE}" >&2
+  echo "❗  Invalid SCRIPT_FILE: ${SCRIPT_FILE}" >&2
   exit 1
 fi
 
 if [[ ! -f ${EXPECTED_FILE} ]];
 then
-  echo "❗ Failed to update expected test. EXPECTED_FILE does not exist: ${EXPECTED_FILE}" >&2
+  echo "❗  Invalid EXPECTED_FILE: ${EXPECTED_FILE}" >&2
   exit 1
 fi
 
 if [[ ! -f ${ACTUAL_FILE} ]];
 then
-  echo "❗ Failed to update expected test. ACTUAL_FILE does not exist: ${ACTUAL_FILE}" >&2
+  echo "❗  Invalid ACTUAL_FILE: ${ACTUAL_FILE}" >&2
   exit 1
 fi
 
