Echo to /dev/stderr for exit 1

diff --git a/bin/download-distro b/bin/download-distro
--- a/bin/download-distro
+++ b/bin/download-distro
@@ -15,7 +15,7 @@ URL="https://cloud-images.ubuntu.com/${VERSION}/current/${FILENAME}"
 # VALIDATE
 
 if [ "${VERSION}" = "" ]; then
-    echo "ERROR: Argument 1 (VERSION) was not provided. Try calling with: jammy"
+    echo "ERROR: Argument 1 (VERSION) was not provided. Try calling with: jammy" >&2
     exit 1
 fi
 
diff --git a/lib/create-proxmox-vm b/lib/create-proxmox-vm
--- a/lib/create-proxmox-vm
+++ b/lib/create-proxmox-vm
@@ -22,13 +22,13 @@ STORAGE_NAME="local"
 
 if [[ "${ID}" = "" ||  "${ID}" -lt "100" || "${ID}" -gt "253" ]];
 then
-    echo "ERROR: Invalid ID: ${ID}"
+    echo "ERROR: Invalid ID: ${ID}" >&2
     exit 1
 fi
 
 if [[ "${MEMORY}" = "" || "${MEMORY}" -lt "1" || "${MEMORY}" -gt "32" ]];
 then
-    echo "ERROR: Invalid MEMORY: ${MEMORY}"
+    echo "ERROR: Invalid MEMORY: ${MEMORY}" >&2
     exit 1
 else
     MEMORY=$((${MEMORY} * 1024))
@@ -36,13 +36,13 @@ fi
 
 if [[ "${CORES}" = "" || "${CORES}" -lt "1" || "${CORES}" -gt "4" ]];
 then
-    echo "ERROR: Invalid CORES: ${CORES}"
+    echo "ERROR: Invalid CORES: ${CORES}" >&2
     exit 1
 fi
 
 if [[ "${DISK_SIZE}" = "" ||  "${DISK_SIZE}" -lt "20" || "${DISK_SIZE}" -gt "4000" ]];
 then
-    echo "ERROR: Invalid DISK_SIZE: ${DISK_SIZE}"
+    echo "ERROR: Invalid DISK_SIZE: ${DISK_SIZE}" >&2
     exit 1
 else
     DISK_SIZE="${DISK_SIZE}G"
@@ -50,7 +50,7 @@ fi
 
 if [[ "${IMG_FILE}" = "" || ! -f "${IMG_FILE}" ]];
 then
-    echo "ERROR: Invalid IMG_FILE: ${IMG_FILE}"
+    echo "ERROR: Invalid IMG_FILE: ${IMG_FILE}" >&2
     exit 1
 fi
 
diff --git a/lib/write-user-config b/lib/write-user-config
--- a/lib/write-user-config
+++ b/lib/write-user-config
@@ -19,7 +19,7 @@ SSH_PORT="4444"
 
 if [[ "${HOSTNAME}" = "" ]];
 then
-    echo "ERROR: Invalid HOSTNAME: ${HOSTNAME}"
+    echo "ERROR: Invalid HOSTNAME: ${HOSTNAME}" >&2
     exit 1
 fi
 
diff --git a/lib/yaml-embed-array b/lib/yaml-embed-array
--- a/lib/yaml-embed-array
+++ b/lib/yaml-embed-array
@@ -14,8 +14,8 @@ TEMP_FILE=$(mktemp)
 # VALIDATE
 
 if [ "${SOURCE_FILE}" = "" ]; then
-    echo "ERROR: Invalid SOURCE_FILE: ${SOURCE_FILE}"
-    exit 1
+  echo "ERROR: Invalid SOURCE_FILE: ${SOURCE_FILE}" >&2
+  exit 1
 fi
 
 # START
diff --git a/tests/lib/run-test b/tests/lib/run-test
--- a/tests/lib/run-test
+++ b/tests/lib/run-test
@@ -15,7 +15,7 @@ EXPECTED_FILE="/srv/tests/expected${SCRIPT_FILE}"
 
 if [[ "${OPTION}" != "--execute" && "${OPTION}" != "--update" ]];
 then
-  echo "FAILED: Invalid OPTION: ${OPTION}"
+  echo "FAILED: Invalid OPTION: ${OPTION}" >&2
   exit 1
 fi
 
@@ -35,7 +35,7 @@ fi
 
 if ! ${SCRIPT_FILE} ${ACTUAL_FILE} ${ARGUMENTS};
 then
-  echo "##### TEST FAILED: The script returned an error code."
+  echo "##### TEST FAILED: The script returned an error code." >&2
   exit 1
 fi
 
