Added vm ssh <ID>

diff --git a/bin/vm b/bin/vm
--- a/bin/vm
+++ b/bin/vm
@@ -23,6 +23,7 @@ ALL=$(get-arg "--all")
 
 declare START_USAGE="$0 start <ID>"
 declare STATUS_USAGE="$0 status <ID>"
+declare SSH_USAGE="$0 ssh <ID>"
 declare DESTROY_USAGE="$0 destroy --all"
 declare CREATE_USAGE="$0 create"
 
@@ -67,16 +68,30 @@ then
 
   /srv/lib/vm/create-vm.sh "$@"
 
+elif [[ "${COMMAND}" == "ssh" ]]
+then
+
+  if [[ "${ID}" != "" ]]
+  then
+    /srv/lib/vm/ssh-vm.sh "${ID}"
+  else
+    echo "❗  Invalid arguments." >&2
+    echo "Usage: ${SSH_USAGE}"
+    exit 1
+  fi
+
 elif [[ "${COMMAND}" == "help" || -v "ARGS[--help]" ]]
 then
   echo "Usage: ${START_USAGE}"
   echo "Usage: ${STATUS_USAGE}"
+  echo "Usage: ${SSH_USAGE}"
   echo "Usage: ${DESTROY_USAGE}"
   echo "Usage: ${CREATE_USAGE}"
 else
   echo "❗  Invalid arguments." >&2
   echo "Usage: ${START_USAGE}"
   echo "Usage: ${STATUS_USAGE}"
+  echo "Usage: ${SSH_USAGE}"
   echo "Usage: ${DESTROY_USAGE}"
   echo "Usage: ${CREATE_USAGE}"
   exit 1
