Added vm destroy --all command

diff --git a/bin/vm b/bin/vm
--- a/bin/vm
+++ b/bin/vm
@@ -16,6 +16,7 @@ declare COMMAND
 
 declare START_USAGE="$0 start <ID>"
 declare STATUS_USAGE="$0 status <ID>"
+declare DESTROY_USAGE="$0 destroy --all"
 declare CREATE_USAGE="$0 create"
 
 if [[ "${COMMAND}" == "start" ]]
@@ -33,7 +34,6 @@ then
     exit 1
   fi
 
-
 elif [[ "${COMMAND}" == "status" ]]
 then
 
@@ -49,6 +49,18 @@ then
     exit 1
   fi
 
+elif [[ "${COMMAND}" == "destroy" ]]
+then
+
+  if [[ -v "ARGS[--all]" ]]
+  then
+    /srv/lib/vm/destroy-stopped-vm.sh
+  else
+    echo "❗  Invalid arguments." >&2
+    echo "Usage: ${DESTROY_USAGE}"
+    exit 1
+  fi
+
 elif [[ "${COMMAND}" == "create" ]]
 then
 
@@ -58,11 +70,13 @@ elif [[ "${COMMAND}" == "help" || -v "ARGS[--help]" ]]
 then
   echo "Usage: ${START_USAGE}"
   echo "Usage: ${STATUS_USAGE}"
+  echo "Usage: ${DESTROY_USAGE}"
   echo "Usage: ${CREATE_USAGE}"
 else
   echo "❗  Invalid arguments." >&2
   echo "Usage: ${START_USAGE}"
   echo "Usage: ${STATUS_USAGE}"
+  echo "Usage: ${DESTROY_USAGE}"
   echo "Usage: ${CREATE_USAGE}"
   exit 1
 fi
