Use for instead of while loop

diff --git a/lib/create-proxmox-vm b/lib/create-proxmox-vm
--- a/lib/create-proxmox-vm
+++ b/lib/create-proxmox-vm
@@ -100,21 +100,18 @@ echo "➡️  Write user config"
 echo "➡️  Write network config"
 /srv/lib/write-network-config "/var/lib/vz/snippets/${ID}-network-config.yml" ${ID}
 
-# echo "➡️  Get status"
-# /srv/lib/get-vm-status "${ID}"
-
-ATTEMPT_COUNT=0
-while :
+# Wait for the maxdisk value to be set
+# If it takes more than 10 attempts then exit
+for i in $(seq "1" "10")
 do
-  ATTEMPT_COUNT=$(( $ATTEMPT_COUNT + 1 ))
   CURRENT_DISK_SIZE=$(/srv/lib/get-vm-status "${ID}" | jq '.maxdisk')
-  if [[ "${ATTEMPT_COUNT}" -gt "10" ]]
+  if [[ "${i}" -ge "10" ]]
   then
-    echo "❗  Unable to resize disk. Exceeded max attempts: ${ATTEMPT_COUNT}" >&2
+    echo "❗  Unable to resize disk. Exceeded max attempts: ${i}" >&2
     exit 1
   elif [[ "${CURRENT_DISK_SIZE}" -lt "2361393152" ]]
   then
-    echo "⌛  Waiting for boot disk. Attempt: ${ATTEMPT_COUNT}"
+    echo "⌛  Waiting for boot disk. Attempt: ${i}"
     sleep 0.2s
   else
     echo "🆗  Boot disk import complete"
@@ -122,18 +119,12 @@ do
   fi
 done
 
-COUNTDOWN=5
-while :
+# Wait some additional time else it will fail
+# TODO: Determine why this is necessary
+for i in $(seq "10" "-1" "1")
 do
-  COUNTDOWN=$(( $COUNTDOWN - 1 ))
-  if [[ "${COUNTDOWN}" -gt "0" ]]
-  then
-    echo "⌛  Waiting ${COUNTDOWN} seconds"
-    sleep 1s
-  else
-    echo "🆗  Countdown complete"
-    break
-  fi
+  echo "⌛  Waiting ${i} seconds"
+  sleep 1s
 done
 
 echo "➡️  Resize boot disk"
